_: !import
  - from pyro.distributions import Uniform
  - from pyrofit.lensing.sources import SersicSource
  - from pyrofit.lensing.utils import get_meshgrid
  - from pyro import distributions as dist
#   - import torch
#   - from get_meshgridXY import get_meshgridX, get_meshgridY, test_import
#   - import get_meshgridX, get_meshgridY
  
defs:
  res: &res ${res=(0.0125)} # with a $ so they can be changed from jypyter
  nx: &nx ${nx=(400)}
  ny: &ny ${ny=(400)}
  XY: !py:get_meshgrid &XY [*res, *nx, *ny]
#   X: !py:get_meshgridX &X [*res, *nx, *ny]
#   Y: !py:get_meshgridX &Y [*res, *nx, *ny]

model: !Stochastic
  - !py:SersicSource []
  - [X, Y]: *XY
    x:     !Sampler [!py:dist.Uniform [-1., 1.]]
    y:     !Sampler [!py:dist.Uniform [-1., 1.]]
    phi:   0
    q:     1
    index: 1
    r_e:   1
    I_e:   5
  
    
# model: !Stochastic
#   - !py:SersicSource
#       <: *XY
#   - x:     !Sampler [!py:dist.Uniform [-1., 1.]]
#     y:     !Sampler [!py:dist.Uniform [-1., 1.]]
#     phi:   0
#     q:     1
#     index: 1
#     r_e:   1
#     I_e:   5
    
guide:
  - cls: MultivariateNormalSamplingGroup
# Why doesn't it work with the following model?


